export * from "./CardAbout";
export * from "./Footer";
export * from "./MenuRedesSociales";
export * from "./ModalAnuncios";
export * from "./PasoComponent";
export * from "./ScrollTop";
export * from "./TableIntegrantes";
export * from "./TableNormativas";
export * from "./TopMenu";
